headlamp:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "le-acme"
    ingressClassName: nginx
    hosts:
      - host: headlamp.michaelbui.dk
        paths:
          - path: /
            type: Prefix
    tls:
      - secretName: headlamp-michaelbui-dk
        hosts:
          - headlamp.michaelbui.dk

