headlamp:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "le-acme"
    ingressClassName: nginx
    hosts:
      - headlamp.michaelbui.dk
    tls:
      - secretName: headlamp-michaelbui-dk
        hosts:
          - headlamp.michaelbui.dk

