apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: prometheus-node-exporter
    release: prometheus
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 3m
      path: /metrics
      targetPort: 9100
      scheme: http
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      jobLabel: node-exporter
