longhorn:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    host: "longhorn.michaelbui.dk"
    tls: true
    tlsSecret: le-longhorn-michaelbui-dk
    path: "/longhorn"
    annotations:
      cert-manager.io/cluster-issuer: "le-acme"

  preUpgradeChecker:
    jobEnabled: false