apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: loadbalancer
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/michaelbui99/homelab
        targetRevision: HEAD
        path: cluster/loadbalancer
    destination:
        server: https://kubernetes.default.svc
        namespace: loadbalancer
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
