apiVersion: v1
kind: Service
metadata:
    name: argo-cd-lb
    labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: argocd-server-lb
        app.kubernetes.io/part-of: argocd
spec:
    selector:
        app.kubernetes.io/name: argocd-server
    ports:
        - port: 80
          targetPort: 8080
    type: LoadBalancer
