kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
    grafana:
      ini:
        server:
          domain: "grafana.michaelbui.dk"
          root_url: "%(protocol)s://%(domain)s:%(http_port)s"
