kube-prometheus-stack:
  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: le-acme
      enabled: true
      ingressClassName: nginx
      hosts:
        - "grafana.michaelbui.dk"
      tls:
        - secretName: le-grafana-michaelbui-dk
          hosts:
            - grafana.michaelbui.dk
  prometheus:
    prometheusSpec:
      serviceMonitorSelector: {}
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: le-acme
      hosts:
        - "prometheus.michaelbui.dk"
      paths:
        - /
      tls:
        - secretName: le-prometheus-michaelbui-dk
          hosts:
            - prometheus.michaelbui.dk
  prometheus-node-exporter:
    releaseLabel: false
