kube-prometheus-stack:
  grafana:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: le-acme
      enabled: true
      ingressClassName: nginx
      hosts:
        - "grafana.michaelbui.dk"
      tls:
        - secretName: le-grafana-michaelbui-dk
          hosts: 
            - grafana.michaelbui.dk