- name: Enable kernal IP forwarding
  hosts: "{{ target_hosts | default('allhosts') }}"
  become: true
  tasks:
      - name: enable
        ansible.builtin.shell: echo 1 > /proc/sys/net/ipv4/ip_forward
