- name: Setup Longhorn Prerequisites
  hosts: allhosts
  become: true
  tasks:
    - name: Install open-iscsi
      ansible.builtin.dnf:
        name:
          - open-iscsi
        state: present

    - name: Install NFSv4 cLient
      ansible.builtin.dnf:
        name:
          - nfs-utils
        state: present
