- name: Setup Longhorn Prerequisites
  hosts: allhosts
  become: true
  tasks:
    - name: Install open-iscsi
      ansible.builtin.dnf:
        name:
          - iscsi-initiator-utils
        state: present

    - name: Post install
      ansible.builtin.shell: |
        echo "InitiatorName=$(/sbin/iscsi-iname)" > /etc/iscsi/initiatorname.iscsi

    - name: Enable iscsid
      ansible.builtin.service:
        name: iscsid
        enabled: true
        state: started
    - name: Install NFSv4 cLient
      ansible.builtin.dnf:
        name:
          - nfs-utils
        state: present
