- name: Update
  hosts: "{{ target_hosts | default('allhosts') }}"
  become: true
  tasks:
      - name: dnf
        ansible.builtin.dnf:
            update_cache: true
            name: "*"
            state: latest
