keycloak:
  metrics:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    hostname: keycloak.michaelbui.dk
    annotations:
      cert-manager.io/cluster-issuer: "le-acme"
    tls: true
  adminIngress:
    enabled: true
    ingressClassName: nginx
    pathType: Prefix
    hostname: keycloak-admin.michaelbui.dk
    annotations:
      cert-manager.io/cluster-issuer: "le-acme"
    tls: true
  keycloakConfigCli:
    enabled: true
    configuration:
      master.json: |
        {
          "realm" : "master",
          "attributes": {
            "frontendUrl": "https://keycloak-admin.michaelbui.dk"
          }
        }
