apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    namespace: argocd
    name: kube-prometheus-stack
spec:
    project: default
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
            - PrunePropagationPolicy=foreground
            - PruneLast=true
            - Replace=false
            - ApplyOutOfSyncOnly=true
    source:
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 58.3.1
        helm:
            releaseName: kube-prometheus-stack
            parameters:
                - name: "granafa.ingress.enabled"
                  value: "true"
    destination:
        server: "https://kubernetes.default.svc"
        namespace: monitoring
