apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    namespace: argocd
    name: kube-prometheus-stack
spec:
    project: default
    source:
        chart: prometheus-community/kube-prometheus-stack
        repoURL: https://github.com/prometheus-community/helm-charts/
        targetRevision: 58.3.1
        helm:
            releaseName: kube-prometheus-stack
    destination:
        server: "https://kubernetes.default.svc"
        namespace: monitoring
