apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michaelbui99/homelab
    targetRevision: HEAD
    path: cluster/infrastructure/alloy
    helm:
      releaseName: alloy
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
