apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michaelbui99/homelab
    targetRevision: HEAD
    path: cluster/keycloak
    helm:
      releaseName: keycloak
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
